name: Testing

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install npm packages
        run: npm install

      - name: Setup environment variables
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> $GITHUB_ENV
          echo "GENERAL_ROLE_GROUP=${{ secrets.GENERAL_ROLE_GROUP }}" >> $GITHUB_ENV
          echo "MANAGER_ROLE_GROUP=${{ secrets.MANAGER_ROLE_GROUP }}" >> $GITHUB_ENV
          echo "NODE_ENV=test" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "EMBEDDING_MODEL=${{ secrets.EMBEDDING_MODEL }}" >> $GITHUB_ENV
          echo "EMBEDDING_DIMENSIONS=${{ secrets.EMBEDDING_DIMENSIONS }}" >> $GITHUB_ENV

      - name: Test code
        run: npm run test

  run-e2e-tests:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install npm packages
        run: npm install

      - name: Setup environment variables
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> $GITHUB_ENV
          echo "GENERAL_ROLE_GROUP=${{ secrets.GENERAL_ROLE_GROUP }}" >> $GITHUB_ENV
          echo "MANAGER_ROLE_GROUP=${{ secrets.MANAGER_ROLE_GROUP }}" >> $GITHUB_ENV
          echo "NODE_ENV=test" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "EMBEDDING_MODEL=${{ secrets.EMBEDDING_MODEL }}" >> $GITHUB_ENV
          echo "EMBEDDING_DIMENSIONS=${{ secrets.EMBEDDING_DIMENSIONS }}" >> $GITHUB_ENV

      - name: Build the Application
        run: npm run build

      - name: Run E2E Tests
        run: npm run test:e2e
